/*
 * Copyright 2025, the AniflowKMP project contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package me.andannn.aniflow.database.util

import me.andannn.aniflow.database.schema.MediaEntity
import me.andannn.aniflow.database.schema.MediaListEntity
import me.andannn.aniflow.database.schema.UserEntity

@Suppress("ktlint:standard:function-naming")
fun MediaEntityWithDefault(
    id: String,
    mediaType: String? = null,
    englishTitle: String? = null,
    romajiTitle: String? = null,
    nativeTitle: String? = null,
    coverImageExtraLarge: String? = null,
    coverImageLarge: String? = null,
    coverImageMedium: String? = null,
    coverImageColor: String? = null,
    description: String? = null,
    episodes: Long? = null,
    seasonYear: Long? = null,
    season: String? = null,
    source: String? = null,
    status: String? = null,
    hashtag: String? = null,
    bannerImage: String? = null,
    averageScore: Long? = null,
    trailerId: String? = null,
    trailerSite: String? = null,
    trailerThumbnail: String? = null,
    genres: String? = null,
    format: String? = null,
    trending: Long? = null,
    favourites: Long? = null,
    popularRanking: Long? = null,
    ratedRanking: Long? = null,
    nextAiringEpisode: Long? = null,
    timeUntilAiring: Long? = null,
    startDate: Long? = null,
    endDate: Long? = null,
    isFavourite: Boolean? = null,
    siteUrl: Long? = null,
) = MediaEntity(
    id = id,
    mediaType = mediaType,
    englishTitle = englishTitle,
    romajiTitle = romajiTitle,
    nativeTitle = nativeTitle,
    coverImageExtraLarge = coverImageExtraLarge,
    coverImageLarge = coverImageLarge,
    coverImageMedium = coverImageMedium,
    coverImageColor = coverImageColor,
    description = description,
    episodes = episodes,
    seasonYear = seasonYear,
    season = season,
    source = source,
    status = status,
    hashtag = hashtag,
    bannerImage = bannerImage,
    averageScore = averageScore,
    trailerId = trailerId,
    trailerSite = trailerSite,
    trailerThumbnail = trailerThumbnail,
    genres = genres,
    format = format,
    trending = trending,
    favourites = favourites,
    popularRanking = popularRanking,
    ratedRanking = ratedRanking,
    nextAiringEpisode = nextAiringEpisode,
    timeUntilAiring = timeUntilAiring,
    isFavourite = isFavourite,
    siteUrl = siteUrl,
)

@Suppress("ktlint:standard:function-naming")
fun UserEntityWithDefault(
    id: String,
    name: String? = null,
    avatarImage: String? = null,
    bannerImage: String? = null,
    profileColor: String? = null,
    unreadNotificationCount: Long? = null,
) = UserEntity(
    id = id,
    name = name,
    bannerImage = bannerImage,
    avatarImage = avatarImage,
    profileColor = profileColor,
    unreadNotificationCount = unreadNotificationCount,
)

@Suppress("ktlint:standard:function-naming")
fun MediaListEntityWithDefault(
    mediaListId: String,
    userId: String? = null,
    mediaId: String? = null,
    listStatus: String? = null,
    notes: String? = null,
    progress: Long? = null,
    progressVolumes: Long? = null,
    startedAt: String? = null,
    completedAt: String? = null,
    updatedAt: Long? = null,
    repeat: Long? = null,
    score: Double? = null,
    isPrivate: Boolean? = null,
) = MediaListEntity(
    mediaListId = mediaListId,
    userId = userId,
    mediaId = mediaId,
    listStatus = listStatus,
    notes = notes,
    progress = progress,
    progressVolumes = progressVolumes,
    startedAt = startedAt,
    completedAt = completedAt,
    updatedAt = updatedAt,
    repeat = repeat,
    score = score,
    isPrivate = isPrivate,
)
